/**
 * Каталог пересчёта единиц лабораторных показателей.
 * unitA — «базовая» (часто SI), unitB — альтернативная.
 * factor: valueB = valueA × factor; valueA = valueB / factor.
 * Коэффициенты — стандартные клинические (Mayo Clinic Laboratories SI Conversion,
 * Labcorp / учебные таблицы SI).
 */

/** @typedef {{ id: string, name: string, unitA: string, unitB: string, factor: number }} Analyte */

/** @type {Analyte[]} */
export const ANALYTES = [
  { id: 'ohp17', name: '17-гидроксипрогестерон', unitA: 'мкг/л', unitB: 'нмоль/л', factor: 3.026 },
  { id: 'c3', name: 'C3 — компонент комплемента', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'c4', name: 'C4 — компонент комплемента', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'ca125', name: 'CA 125', unitA: 'кЕд/л', unitB: 'Ед/мл', factor: 1 },
  { id: 'ca19-9', name: 'CA 19-9', unitA: 'кЕд/л', unitB: 'Ед/мл', factor: 1 },
  { id: 'ca72-4', name: 'CA 72-4', unitA: 'кЕд/л', unitB: 'Ед/мл', factor: 1 },
  { id: 'cyfra21-1', name: 'Cyfra-21-1', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'c-peptide', name: 'C-пептид', unitA: 'нмоль/л', unitB: 'нг/мл', factor: 3.02 },
  { id: 'crp', name: 'C-реактивный протеин', unitA: 'мг/л', unitB: 'мг/дл', factor: 0.1 },
  { id: 'dheas', name: 'DHEA-S', unitA: 'мг/л', unitB: 'мкмоль/л', factor: 2.714 },
  { id: 'nse', name: 'NSE', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'p1np', name: 'P1NP', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'ubc', name: 'UBC', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'b-cross-laps', name: 'B-Cross laps', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'adrenaline-u', name: 'Адреналин в моче', unitA: 'мкг/24 ч', unitB: 'нмоль/сут', factor: 5.458 },
  { id: 'acth', name: 'АКТГ', unitA: 'нг/л', unitB: 'пмоль/л', factor: 0.22 },
  { id: 'albumin', name: 'Альбумин', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'aldosterone', name: 'Альдостерон', unitA: 'нг/л', unitB: 'пмоль/л', factor: 2.774 },
  { id: 'orosomucoid', name: 'Альфа-1-кислый гликопротеин', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'androstenedione', name: 'Андростендион', unitA: 'мкг/л', unitB: 'нмоль/л', factor: 3.49 },
  { id: 'apo-a', name: 'Аполипопротеин A', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'apo-b', name: 'Аполипопротеин В', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'papp-a', name: 'Ассоциированный с беременностью плазменный белок А', unitA: 'МЕ/л', unitB: 'мМЕ/мл', factor: 1 },
  { id: 'afp', name: 'АФП', unitA: 'кЕд/л', unitB: 'Ед/мл', factor: 1 },
  { id: 's100', name: 'Белок S100', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'b2m', name: 'Бета-2-микроглобулин', unitA: 'мг/л', unitB: 'мкг/мл', factor: 1 },
  { id: 'bili-indirect', name: 'Билирубин непрямой', unitA: 'мкмоль/л', unitB: 'мг/дл', factor: 0.05848 },
  { id: 'bili-total', name: 'Билирубин общий', unitA: 'мкмоль/л', unitB: 'мг/дл', factor: 0.05848 },
  { id: 'bili-direct', name: 'Билирубин прямой', unitA: 'мкмоль/л', unitB: 'мг/дл', factor: 0.05848 },
  { id: 'vma-u', name: 'Ванилилминдальная кислота в моче', unitA: 'мг/24 ч', unitB: 'мкмоль/сут', factor: 5.046 },
  { id: 'b12', name: 'Витамин В12', unitA: 'пмоль/л', unitB: 'пг/мл', factor: 1.355 },
  { id: 'haptoglobin', name: 'Гаптоглобин', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'glucose', name: 'Глюкоза', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 18.0182 },
  { id: 'homocysteine', name: 'Гомоцистеин', unitA: 'мкмоль/л', unitB: 'мкг/мл', factor: 0.1352 },
  { id: 'dpd-u', name: 'Дезоксипиридинолин в моче', unitA: 'нмоль ДПД/ммоль Кр', unitB: 'мкг ДПД/г Кр', factor: 0.35 },
  { id: 'dht', name: 'Дигидротестостерон', unitA: 'нг/л', unitB: 'нмоль/л', factor: 0.003443 },
  { id: 'dopamine-u', name: 'Дофамин в моче', unitA: 'мкг/24 ч', unitB: 'нмоль/сут', factor: 6.528 },
  { id: 'iron', name: 'Железо', unitA: 'мкмоль/л', unitB: 'мкг/дл', factor: 5.585 },
  { id: 'iga', name: 'Иммуноглобулин A', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'igg', name: 'Иммуноглобулин G', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'igm', name: 'Иммуноглобулин M', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'ige', name: 'Иммуноглобулин Е', unitA: 'кЕд/л', unitB: 'Ед/мл', factor: 1 },
  { id: 'insulin', name: 'Инсулин', unitA: 'мМЕ/л', unitB: 'мкМЕ/мл', factor: 1 },
  { id: 'iodine', name: 'Йод', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'igf1', name: 'ИПФР-1 (Соматомедин С)', unitA: 'мкг/л', unitB: 'нмоль/л', factor: 0.1307 },
  { id: 'potassium', name: 'Калий', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 3.91 },
  { id: 'ca-ion', name: 'Кальций ионизированный', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 4.008 },
  { id: 'ca-total', name: 'Кальций общий', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 4.008 },
  { id: 'calcitonin', name: 'Кальцитонин', unitA: 'нг/л', unitB: 'пмоль/л', factor: 0.281 },
  { id: 'ecp', name: 'Катионный протеин эозинофилов', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'cortisol', name: 'Кортизол', unitA: 'мкг/л', unitB: 'нмоль/л', factor: 2.76 },
  { id: 'creatinine', name: 'Креатинин', unitA: 'мкмоль/л', unitB: 'мг/дл', factor: 0.01131 },
  { id: 'lactate', name: 'Лактат', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 9.008 },
  { id: 'lh', name: 'ЛГ', unitA: 'МЕ/л', unitB: 'мМЕ/мл', factor: 1 },
  { id: 'lpa', name: 'Липопротеин (а)', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'magnesium', name: 'Магний', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 2.431 },
  { id: 'copper', name: 'Медь', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'myoglobin', name: 'Миоглобин', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'uric-acid', name: 'Мочевая кислота', unitA: 'мкмоль/л', unitB: 'мг/дл', factor: 0.01681 },
  { id: 'urea', name: 'Мочевина', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 6.006 },
  { id: 'sodium', name: 'Натрий', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 2.3 },
  { id: 'noradrenaline-u', name: 'Норадреналин в моче', unitA: 'мкг/24 ч', unitB: 'нмоль/сут', factor: 5.911 },
  { id: 'osteocalcin', name: 'Остеокальцин', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'bap', name: 'Остаза', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'pth', name: 'Паратгормон', unitA: 'нг/л', unitB: 'пмоль/л', factor: 0.106 },
  { id: 'hpl', name: 'Плацентарный лактоген', unitA: 'мг/л', unitB: 'мкг/мл', factor: 1 },
  { id: 'progesterone', name: 'Прогестерон', unitA: 'мкг/л', unitB: 'нмоль/л', factor: 3.18 },
  { id: 'prolactin', name: 'Пролактин', unitA: 'мкг/л', unitB: 'мМЕ/л', factor: 21.2 },
  { id: 'pap', name: 'Простатическая кислая фосфатаза (PAP)', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'psa-total', name: 'ПСА общий', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'psa-free', name: 'ПСА свободный', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'stfr', name: 'Растворимые рецепторы трансферрина', unitA: 'мг/л', unitB: 'мкг/мл', factor: 1 },
  { id: 'renin', name: 'Ренин прямой', unitA: 'нг/л', unitB: 'пг/мл', factor: 1 },
  { id: 'cea', name: 'РЭА', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'ca15-3', name: 'СА 15-3', unitA: 'кЕд/л', unitB: 'Ед/мл', factor: 1 },
  { id: 'free-bhcg', name: 'Свободная B-субъединица ХГЧ', unitA: 'МЕ/л', unitB: 'нг/мл', factor: 1 },
  { id: 'selenium', name: 'Селен', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'gh', name: 'СТГ', unitA: 'мкг/л', unitB: 'мМЕ/л', factor: 3 },
  { id: 't3-total', name: 'Т3 общий', unitA: 'нмоль/л', unitB: 'нг/дл', factor: 65.1 },
  { id: 't3-free', name: 'Т3 свободный', unitA: 'пмоль/л', unitB: 'пг/мл', factor: 0.651 },
  { id: 't4-total', name: 'Т4 общий', unitA: 'нмоль/л', unitB: 'мкг/дл', factor: 0.0777 },
  { id: 't4-free', name: 'Т4 свободный', unitA: 'пмоль/л', unitB: 'нг/дл', factor: 0.0777 },
  { id: 'thyroglobulin', name: 'ТГ (тиреоглобулин)', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'testosterone-free', name: 'Тестостерон свободный', unitA: 'нг/л', unitB: 'пмоль/л', factor: 3.47 },
  { id: 'testosterone', name: 'Тестостерон', unitA: 'мкг/л', unitB: 'нмоль/л', factor: 3.47 },
  { id: 'tbg', name: 'Тироксинсвязывающий глобулин', unitA: 'мг/л', unitB: 'нмоль/л', factor: 18.5 },
  { id: 'transferrin', name: 'Трансферрин', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'triglycerides', name: 'Триглицериды', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 88.57 },
  { id: 'troponin-i', name: 'Тропонин I', unitA: 'мкг/л', unitB: 'нг/мл', factor: 1 },
  { id: 'tsh', name: 'ТТГ', unitA: 'мМЕ/л', unitB: 'мкМЕ/мл', factor: 1 },
  { id: 'ferritin', name: 'Ферритин', unitA: 'мкг/л', unitB: 'пмоль/л', factor: 2.247 },
  { id: 'folate', name: 'Фолиевая кислота', unitA: 'нмоль/л', unitB: 'нг/мл', factor: 0.441 },
  { id: 'phosphorus', name: 'Фосфор неорганический', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 3.097 },
  { id: 'fsh', name: 'ФСГ', unitA: 'МЕ/л', unitB: 'нг/мл', factor: 0.14 },
  { id: 'hcg', name: 'ХГЧ', unitA: 'МЕ/л', unitB: 'мМЕ/мл', factor: 1 },
  { id: 'chloride', name: 'Хлориды', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 3.545 },
  { id: 'chol-total', name: 'Холестерин общий', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 38.67 },
  { id: 'chol-hdl', name: 'Холестерин-ЛПВП', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 38.67 },
  { id: 'chol-ldl', name: 'Холестерин-ЛПНП', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 38.67 },
  { id: 'chol-vldl', name: 'Холестерин-ЛПОНП', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 38.67 },
  { id: 'ceruloplasmin', name: 'Церулоплазмин', unitA: 'г/л', unitB: 'г/дл', factor: 0.1 },
  { id: 'zinc', name: 'Цинк', unitA: 'мкмоль/л', unitB: 'мкг/дл', factor: 6.538 },
  { id: 'epo', name: 'Эритропоэтин', unitA: 'МЕ/л', unitB: 'мМЕ/мл', factor: 1 },
  { id: 'estradiol', name: 'Эстрадиол', unitA: 'нг/л', unitB: 'пмоль/л', factor: 3.671 },
  { id: 'estriol-free', name: 'Эстриол свободный', unitA: 'мкг/л', unitB: 'нмоль/л', factor: 3.467 },

  // Mayo Clinic Laboratories — SI Unit Conversion (дополнение к каталогу)
  // CF Mayo: conventional × CF = SI; у нас unitA=SI, unitB=conventional, factor = 1/CF
  { id: 'vitamin-d-total', name: '25-OH витамин D (общий)', unitA: 'нмоль/л', unitB: 'нг/мл', factor: 0.400641 },
  { id: 'vitamin-d2', name: '25-OH витамин D2', unitA: 'нмоль/л', unitB: 'нг/мл', factor: 0.412711 },
  { id: 'vitamin-d3', name: '25-OH витамин D3', unitA: 'нмоль/л', unitB: 'нг/мл', factor: 0.400641 },
  { id: 'vitamin-d-125', name: '1,25-(OH)₂ витамин D', unitA: 'пмоль/л', unitB: 'пг/мл', factor: 0.416667 },
  { id: 'methoxytyramine-u', name: '3-Метокситирамин в моче', unitA: 'нмоль/сут', unitB: 'мкг/24 ч', factor: 0.167196 },
  { id: 'ace', name: 'АПФ (ангиотензинпревращающий фермент)', unitA: 'мкКат/л', unitB: 'Ед/л', factor: 58.8235 },
  { id: 'aluminum', name: 'Алюминий', unitA: 'мкмоль/л', unitB: 'нг/мл', factor: 26.9542 },
  { id: 'aldosterone-u', name: 'Альдостерон в моче', unitA: 'нмоль/сут', unitB: 'мкг/24 ч', factor: 0.36049 },
  { id: 'gastrin', name: 'Гастрин', unitA: 'нг/л', unitB: 'пг/мл', factor: 1 },
  { id: 'glucagon', name: 'Глюкагон', unitA: 'нг/л', unitB: 'пг/мл', factor: 1 },
  { id: 'glucose-csf', name: 'Глюкоза (ликвор / ЦСЖ)', unitA: 'ммоль/л', unitB: 'мг/дл', factor: 18.0182 },
  { id: 'dhea', name: 'ДГЭА (дегидроэпиандростерон)', unitA: 'нмоль/л', unitB: 'нг/мл', factor: 0.288433 },
  { id: 'deoxycortisol-11', name: '11-Дезоксикортизол', unitA: 'нмоль/л', unitB: 'нг/дл', factor: 34.6021 },
  { id: 'insulin-pmol', name: 'Инсулин (пмоль/л)', unitA: 'пмоль/л', unitB: 'мкМЕ/мл', factor: 0.143885 },
  { id: 'adrenaline-p', name: 'Адреналин (плазма)', unitA: 'пмоль/л', unitB: 'пг/мл', factor: 0.183218 },
  { id: 'noradrenaline-p', name: 'Норадреналин (плазма)', unitA: 'пмоль/л', unitB: 'пг/мл', factor: 0.169177 },
  { id: 'dopamine-p', name: 'Дофамин (плазма)', unitA: 'пмоль/л', unitB: 'пг/мл', factor: 0.153186 },
  { id: 'cortisol-u', name: 'Кортизол в моче', unitA: 'нмоль/сут', unitB: 'мкг/24 ч', factor: 0.362319 },
  { id: 'creatinine-u-24h', name: 'Креатинин в моче (сутки)', unitA: 'ммоль/сут', unitB: 'мг/24 ч', factor: 113.122 },
  { id: 'metanephrine-u', name: 'Метанефрин в моче', unitA: 'нмоль/сут', unitB: 'мкг/24 ч', factor: 0.197239 },
  { id: 'normetanephrine-u', name: 'Норметанефрин в моче', unitA: 'нмоль/сут', unitB: 'мкг/24 ч', factor: 0.183218 },
  { id: 'metanephrines-total-u', name: 'Метанефрины суммарно (моча)', unitA: 'нмоль/сут', unitB: 'мкг/24 ч', factor: 0.18997 },
  { id: 'osmolality', name: 'Осмоляльность сыворотки', unitA: 'ммоль/кг', unitB: 'мОсм/кг', factor: 1 },
  { id: 'serotonin', name: 'Серотонин', unitA: 'нмоль/л', unitB: 'нг/мл', factor: 0.176211 },
  { id: 'estrone', name: 'Эстрон', unitA: 'пмоль/л', unitB: 'пг/мл', factor: 0.270343 },
];

const BY_ID = new Map(ANALYTES.map((a) => [a.id, a]));

export function getAnalyte(id) {
  return BY_ID.get(id) || null;
}

export function listAnalytes() {
  return ANALYTES.slice();
}
